spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
  flyway:
    locations: classpath:db/migration/{vendor}
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
    test-connection: false
  messages:
    basename: messages

system:
  configuration:
    api-endpoint: '/api'
    oidc-admin-group-name: 'burning-okr-admin'
    client-id: 'burning-okr-client'
    issuer-uri: 'http://localhost:9090/realms/burning-okr'
    scopes:
      - 'profile'
      - 'offline_access'
      - 'openid'
      - 'email'
    strict-discovery-document-validation: true
    demo-mode: false

